import type {
  Construction,
  Economics,
  HouseholdTerms,
  Regulations,
  SiteConditions,
  SiteFilters,
  SliderDef,
} from "./types";

export const CONSTRAINT = {
  lotSize: "Below minimum lot area",
  envelope: "Setbacks exceed buildable area",
  frontage: "Insufficient frontage",
  units: "Exceeds units per parcel",
  adu: "ADU not permitted",
  stories: "Exceeds height limit",
  parking: "Parking cannot be accommodated",
  steep: "Steep slope",
  flood: "Flood zone",
  landslide: "Landslide-prone",
  undermined: "Undermined",
  noWater: "No water service",
  stepsOnly: "Stairs-only access",
  greenway: "Greenway",
  notFeasibleLand: "Not feasible — land cost",
  notFeasibleSite: "Not feasible — site conditions",
  notFeasiblePrice: "Not feasible — sale prices",
  notAffordable: "Not affordable at household income",
} as const;

export const regulationSliders: SliderDef[] = [
  {
    key: "minLotSf",
    label: "Minimum lot area",
    explanation: "A parcel must be at least this large to be developed.",
    min: 0,
    max: 10_000,
    step: 100,
    default: 3000,
    codeReference: "§903.03",
    panel: "regulations",
  },
  {
    key: "frontSetbackFt",
    label: "Front setback",
    explanation: "Required distance from the front property line.",
    min: 0,
    max: 40,
    step: 1,
    default: 30,
    codeReference: "§903.03",
    panel: "regulations",
  },
  {
    key: "rearSetbackFt",
    label: "Rear setback",
    explanation: "Required distance from the rear property line.",
    min: 0,
    max: 40,
    step: 1,
    default: 30,
    codeReference: "§903.03",
    panel: "regulations",
  },
  {
    key: "sideSetbackFt",
    label: "Side setback",
    explanation: "Required distance from each side property line.",
    min: 0,
    max: 20,
    step: 1,
    default: 5,
    codeReference: "§903.03",
    panel: "regulations",
  },
  {
    key: "maxStories",
    label: "Height limit",
    explanation: "Maximum building height, in stories.",
    min: 1,
    max: 12,
    step: 1,
    default: 2,
    codeReference: "§903.03",
    panel: "regulations",
  },
  {
    key: "unitsPerLot",
    label: "Units per parcel",
    explanation: "Maximum dwelling units on one parcel.",
    min: 1,
    max: 60,
    step: 1,
    default: 1,
    codeReference: "§911.02",
    panel: "regulations",
  },
  {
    key: "parkingPerUnit",
    label: "Parking per unit",
    explanation: "Off-street parking spaces required per dwelling unit.",
    min: 0,
    max: 2,
    step: 1,
    default: 1,
    codeReference: "Ch. 914",
    panel: "regulations",
  },
  {
    key: "aduAllowed",
    label: "ADUs permitted",
    explanation: "Whether an accessory dwelling unit is permitted on the parcel.",
    min: 0,
    max: 1,
    step: 1,
    default: false,
    codeReference: "Ch. 912",
    panel: "regulations",
  },
];

export const DEFAULT_REGULATIONS: Regulations = {
  minLotSf: 3000,
  frontSetbackFt: 30,
  rearSetbackFt: 30,
  sideSetbackFt: 5,
  maxStories: 2,
  unitsPerLot: 1,
  parkingPerUnit: 1,
  aduAllowed: false,
};

export const DEFAULT_CONSTRUCTION: Construction = {
  widthFt: 24,
  depthFt: 40,
  stories: 2,
  units: 1,
  attached: false,
  adu: false,
};

export const DEFAULT_SITE_CONDITIONS: SiteConditions = {
  skipSteep: true,
  skipFlood: true,
  skipLandslide: true,
  skipUndermined: true,
  skipGreenway: true,
  skipNoWater: true,
  skipStepsOnly: true,
  minFrontageFt: 20,
};

export const DEFAULT_SITE_FILTERS: SiteFilters = {
  vacantOnly: false,
  owner: "any",
  districts: [],
  nearTransitOnly: false,
  delinquentOrForeclosedOnly: false,
};

export const economicsSliders: SliderDef[] = [
  {
    key: "buildCostPerSf",
    label: "Construction cost per sq ft",
    explanation:
      "Hard cost per finished square foot, excluding land. Land and site conditions are added from parcel records.",
    min: 80,
    max: 400,
    step: 5,
    default: 260,
    source: "237 N Aiken actual, 2023–24",
    panel: "economics",
    role: "DEVELOPER",
  },
  {
    key: "salePricePerSf",
    label: "Sale price per sq ft",
    explanation: "Market value per finished square foot.",
    min: 60,
    max: 500,
    step: 5,
    default: 160,
    source: "WPRDC sales, prior 24 months, retrieved 2026-09-26",
    panel: "economics",
    role: "MARKET",
  },
  {
    key: "buyerIncome",
    label: "Household income",
    explanation: "The household the units should be affordable to.",
    min: 30_000,
    max: 250_000,
    step: 1_000,
    default: 79_500,
    source: "HUD FY2026, 80% of area median, 3-person household",
    panel: "economics",
    role: "HOUSEHOLD",
  },
  {
    key: "subsidyPerUnit",
    label: "Subsidy per unit",
    explanation: "Public capital contributed per unit.",
    min: 0,
    max: 150_000,
    step: 5_000,
    default: 0,
    source: "user-defined",
    panel: "economics",
    role: "PUBLIC",
  },
  {
    key: "buildingPace",
    label: "Building pace",
    explanation: "New residential units the city builds per year.",
    min: 50,
    max: 3_000,
    step: 25,
    default: 275,
    source: "City of Pittsburgh PLI permits, last three full years (2023–2025)",
    panel: "economics",
    role: "MARKET",
  },
];

export const DEFAULT_ECONOMICS: Economics = {
  buildCostPerSf: 260,
  salePricePerSf: 160,
  buyerIncome: 79_500,
  subsidyPerUnit: 0,
  buildingPace: 275,
};

export const DEFAULT_HOUSEHOLD: HouseholdTerms = {
  mortgageRate: 0.0703,
  downPaymentPct: 0.035,
  incomeToHousing: 0.3,
  propertyTaxRate: 0.015,
  insurancePerMonth: 125,
};

export const householdSliders: SliderDef[] = [
  {
    key: "mortgageRate",
    label: "Mortgage rate",
    explanation: "Freddie Mac PMMS, week of Sept 24, 2026.",
    min: 4,
    max: 9,
    step: 0.05,
    default: 7.03,
    source: "Freddie Mac PMMS 2026-09-24",
    panel: "economics",
  },
  {
    key: "downPaymentPct",
    label: "Down payment",
    explanation: "Share of price paid in cash at purchase.",
    min: 3.5,
    max: 25,
    step: 0.5,
    default: 3.5,
    source: "assumed",
    panel: "economics",
  },
  {
    key: "incomeToHousing",
    label: "Income to housing",
    explanation: "Share of household income spent on housing.",
    min: 25,
    max: 40,
    step: 1,
    default: 30,
    source: "assumed",
    panel: "economics",
  },
  {
    key: "propertyTaxRate",
    label: "Property tax rate",
    explanation: "Effective rate on unit price.",
    min: 0.5,
    max: 3,
    step: 0.05,
    default: 1.5,
    source: "assumed",
    panel: "economics",
  },
  {
    key: "insurancePerMonth",
    label: "Insurance",
    explanation: "Monthly homeowners insurance.",
    min: 50,
    max: 300,
    step: 5,
    default: 125,
    source: "assumed",
    panel: "economics",
  },
];

export function dwellingUnits(construction: Construction): number {
  return construction.units + (construction.adu ? 1 : 0);
}
